#!/usr/bin/env npx ts-node --project tsconfig.json
/**
 * @file reauth-google.ts
 * @description Re-authorise Google OAuth for both dev and prod redirect URIs.
 * Generates two refresh tokens and writes them to google-tokens.txt.
 *
 * Run:  npx tsx scripts/reauth-google.ts
 */

import * as readline from "readline";
import * as fs from "fs";
import * as dotenv from "dotenv";
import { google } from "googleapis";

dotenv.config({ path: ".env.local" });

const clientId = process.env.GOOGLE_OAUTH_CLIENT_ID;
const clientSecret = process.env.GOOGLE_OAUTH_CLIENT_SECRET;

if (!clientId || !clientSecret) {
  console.error("Missing env vars: GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET");
  process.exit(1);
}

const DEV_REDIRECT = "http://localhost:3000/api/google/oauth/callback";
const PROD_REDIRECT = "https://www.tothepoint.co.nz/api/google/oauth/callback";

const SCOPES = [
  "https://www.googleapis.com/auth/calendar",
  "https://www.googleapis.com/auth/contacts",
  "https://www.googleapis.com/auth/spreadsheets",
  "https://www.googleapis.com/auth/drive",
];

/**
 * Prompts the user for a line of input.
 * @param rl - Readline interface.
 * @param question - Question to display.
 * @returns The user's answer.
 */
function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => rl.question(question, resolve));
}

/**
 * Extracts the auth code from a full redirect URL or returns the input as-is.
 * @param input - Raw input from the user (full URL or bare code).
 * @returns The auth code string.
 */
function extractCode(input: string): string {
  const trimmed = input.trim();
  try {
    const parsed = new URL(trimmed);
    return parsed.searchParams.get("code") ?? trimmed;
  } catch {
    return trimmed;
  }
}

/**
 * Generates an auth URL and exchanges the code for a refresh token.
 * @param rl - Readline interface.
 * @param label - Human-readable label (e.g. "dev" or "prod").
 * @param redirectUri - The OAuth redirect URI for this environment.
 * @returns The refresh token string, or null on failure.
 */
async function authorise(
  rl: readline.Interface,
  label: string,
  redirectUri: string,
): Promise<string | null> {
  const client = new google.auth.OAuth2(clientId, clientSecret, redirectUri);
  const authUrl = client.generateAuthUrl({
    access_type: "offline",
    prompt: "consent",
    scope: SCOPES,
  });

  console.log(`\n--- ${label.toUpperCase()} (${redirectUri}) ---`);
  console.log("Open this URL in your browser:\n");
  console.log(`  ${authUrl}\n`);

  const input = await ask(rl, "Paste the full redirect URL (or just the code): ");
  const code = extractCode(input);

  try {
    const { tokens } = await client.getToken(code);
    if (!tokens.refresh_token) {
      console.warn(
        `WARNING: No refresh_token returned for ${label}.\n` +
          "Revoke access at https://myaccount.google.com/permissions and run the script again.",
      );
      return null;
    }
    console.log(`✓ Got ${label} token.`);
    return tokens.refresh_token;
  } catch (err) {
    console.error(`Failed to exchange code for ${label} token:`, err);
    return null;
  }
}

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

console.log("\n=== Google OAuth Re-authorisation (dev + prod) ===");
console.log("You will authorise twice - once for dev, once for prod.");
console.log("Make sure both redirect URIs are registered in Google Cloud Console.\n");

(async () => {
  const devToken = await authorise(rl, "dev", DEV_REDIRECT);
  const prodToken = await authorise(rl, "prod", PROD_REDIRECT);
  rl.close();

  const lines: string[] = [
    "# Google OAuth Refresh Tokens",
    "# Generated by scripts/reauth-google.ts",
    "",
    "# .env.local (dev)",
    `GOOGLE_OAUTH_REFRESH_TOKEN="${devToken ?? "FAILED - run script again"}"`,
    "",
    "# Vercel / .env.production.local (prod)",
    `GOOGLE_OAUTH_REFRESH_TOKEN="${prodToken ?? "FAILED - run script again"}"`,
  ];

  const outPath = "google-tokens.txt";
  fs.writeFileSync(outPath, lines.join("\n") + "\n");

  console.log(`\n=== Done! Tokens written to ${outPath} ===`);
  console.log("  1. Copy the dev token into .env.local");
  console.log("  2. Copy the prod token into .env.production.local, then import to Vercel");
  console.log("  3. Delete google-tokens.txt when done\n");
})();
